### ISSUE TITLE
Email subscription form

### ISSUE THREAD

**Issue by zulhfreelancer** [devopsrepohq/vpc#1]
Hi,

First of all, apologies if this is not the right repo. I tried to find the repo for your [website](https://devopsrepo.com/) but I couldn't find it. I'd like to suggest you to create an email subscription section in your website so people can subscribe to receive updates when you publish new posts/CDK snippets. 

Or, maybe start with Twitter account because there are many devs on Twitter too.

Thanks.

**Comment by zulhfreelancer** [comment]
Off-topic: if I have some CDK snippets to share/edit, how to contribute?

**Comment by thattimc** [comment]
Hi, @zulhfreelancer I really appreciate your valuable feedback. Since I just starting this website, so email subscription section may not so obvious and it indeed exists inside each post content. I will make it on the front page so it will be easy for people to subscribe. What do you think?

I have [twitter](https://twitter.com/csytim) and will keep updating any news there too.

I am really welcome for any contribution, if you don't mind I can add you as collaborators. 🙏

**Comment by zulhfreelancer** [comment]
Thanks @timshingyu. Definitely will subscribe to your newsletter. WRT becoming collaborator, I think I'm good without that for now. If I do find anything to share, I'll fork your repo(s) and submit PRs to you. Keep shipping useful CDK stuffs!
